# Generated by Django 4.0 on 2021-12-25 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.ImageField(blank=True, null=True, upload_to='media/')),
                ('img1', models.ImageField(blank=True, null=True, upload_to='media/')),
                ('img2', models.ImageField(blank=True, null=True, upload_to='media/')),
                ('img3', models.ImageField(blank=True, null=True, upload_to='media/')),
                ('haqqinda', models.TextField(default='Lorem ipsum dolor sit amet')),
                ('name', models.TextField(help_text='name of the product')),
                ('price', models.CharField(default='299$', max_length=155)),
                ('slug', models.SlugField(blank=True, editable=False, unique=True)),
            ],
        ),
    ]
