# Generated by Django 4.0.1 on 2022-01-19 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.ImageField(blank=True, null=True, upload_to='media/')),
                ('haqqinda', models.TextField(default='Lorem ipsum dolor sit amet')),
                ('name', models.CharField(max_length=155)),
                ('price', models.CharField(default='299$', max_length=155)),
                ('slug', models.SlugField(blank=True, editable=False, unique=True)),
                ('designer', models.CharField(default='ABCart', max_length=155)),
                ('brand', models.CharField(blank=True, default='---', max_length=250, null=True)),
                ('Count', models.BigIntegerField()),
                ('informations', models.TextField(help_text='mehsul haqqinda melumat')),
            ],
        ),
        migrations.CreateModel(
            name='Image_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, null=True, upload_to='media/')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='product.product')),
            ],
        ),
    ]
