# Generated by Django 4.0.1 on 2022-05-22 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_quantity_alter_shopcart_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopcart',
            name='quantity',
        ),
    ]
