# Generated by Django 4.0.1 on 2022-05-29 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_brand_remove_product_tag_delete_tag_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(default='ABCart', max_length=155),
        ),
    ]
