# Generated by Django 4.0.1 on 2022-05-29 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_alter_product_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(null=b'I01\n', on_delete=django.db.models.deletion.DO_NOTHING, to='product.brand'),
        ),
    ]
