# Generated by Django 4.0 on 2022-01-01 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countries',
            name='country',
            field=models.TextField(blank=True, max_length=127, null=True),
        ),
        migrations.AlterField(
            model_name='town',
            name='city',
            field=models.TextField(blank=True, max_length=127, null=True),
        ),
    ]
