# Generated by Django 4.0 on 2022-01-01 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_countries_country_alter_town_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countries',
            name='country',
            field=models.TextField(blank=True, default='Azerbaidjan', max_length=127, null=True),
        ),
        migrations.AlterField(
            model_name='town',
            name='city',
            field=models.TextField(blank=True, default='Baki', max_length=127, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Towns', to='accounts.town'),
        ),
        migrations.AlterField(
            model_name='user',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Countries', to='accounts.countries'),
        ),
    ]
