# Generated by Django 4.0 on 2022-01-01 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_countries_country_alter_town_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='city',
        ),
        migrations.AddField(
            model_name='countries',
            name='city',
            field=models.CharField(blank=True, default='Baki', max_length=127, null=True),
        ),
        migrations.AlterField(
            model_name='countries',
            name='country',
            field=models.CharField(blank=True, default='Azerbaidjan', max_length=127, null=True),
        ),
        migrations.DeleteModel(
            name='Town',
        ),
    ]
