# Generated by Django 4.0 on 2021-12-25 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/')),
                ('slogan', models.TextField(default='Far far away, behind the word mountains, far from the countries Vokalia and Consonantia')),
                ('daily_visitor', models.IntegerField(default=10)),
                ('adress', models.TextField(help_text="enter company's current adress")),
                ('phone', models.CharField(default='+2 392 3929 210', max_length=155)),
                ('email', models.CharField(default='\tinfo@yourdomain.com', max_length=123)),
                ('twitter', models.URLField(blank=True, null=True)),
                ('facebook', models.URLField(blank=True, null=True)),
                ('instagram', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Index',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.ImageField(blank=True, null=True, upload_to='media/')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='media/')),
                ('haqqinda', models.TextField(default='Lorem ipsum dolor sit amet')),
                ('name', models.TextField(help_text='name of the product')),
                ('price', models.CharField(default='299$', max_length=155)),
            ],
        ),
    ]
