# Generated by Django 4.0.1 on 2022-04-17 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_alter_shopcart_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopcart',
            name='product',
        ),
        migrations.RemoveField(
            model_name='shopcart',
            name='user',
        ),
    ]
