# Generated by Django 4.0.1 on 2022-05-01 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_shopcart_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopcart',
            name='quantity',
            field=models.CharField(default=1, max_length=155),
            preserve_default=False,
        ),
    ]
