# Generated by Django 4.0.1 on 2022-05-01 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_remove_shopcart_name_remove_shopcart_price_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShopCart',
        ),
    ]
